/**
 *? Generated by meta_gen filter
 *! Edits will be discrded!
 */

/**
 * Contains meta information about the pack, such as version and git info.
 * This information is generated at build time and can be used in the code to display version info or for debugging purposes.
 */
const Meta = {
  manifest: {
    bp: {
      version: "0.0.5",
      min_engine_version: "1.26.30",
    },
    rp: {
      version: "0.0.5",
      min_engine_version: "1.26.10",
    },
  },
  github: {
    commit: undefined,
    tag: undefined,
  },
} as const;

export default Meta;
